meta_product_name: "We Chef"
meta_title: "We Chef - Hire a Chef taylored to your needs"
meta_description: "Easy, fast and efficient way to hire a freelance chef when you need the most"
meta_image: "cover.png"                       # should exist in `app/assets/images/`
